package llm

import (
	"encoding/json"
	"time"
)

// ChatRequest represents a chat completion request
type ChatRequest struct {
	// Model to use for completion (e.g., "gpt-4", "claude-3-opus")
	Model string `json:"model"`
	
	// Messages in the conversation
	Messages []ChatMessage `json:"messages"`
	
	// Tools available for the model to use
	Tools []ToolDefinition `json:"tools,omitempty"`
	
	// How the model should use tools ("none", "auto", "required", or specific tool)
	ToolChoice interface{} `json:"tool_choice,omitempty"`
	
	// Sampling temperature (0.0 to 2.0, higher = more random)
	Temperature *float64 `json:"temperature,omitempty"`
	
	// Maximum tokens to generate
	MaxTokens *int `json:"max_tokens,omitempty"`
	
	// Whether to stream the response
	Stream bool `json:"stream,omitempty"`
	
	// System prompt/instructions
	SystemPrompt string `json:"system,omitempty"`
	
	// Top-p nucleus sampling parameter
	TopP *float64 `json:"top_p,omitempty"`
	
	// Frequency penalty (-2.0 to 2.0)
	FrequencyPenalty *float64 `json:"frequency_penalty,omitempty"`
	
	// Presence penalty (-2.0 to 2.0)  
	PresencePenalty *float64 `json:"presence_penalty,omitempty"`
	
	// Stop sequences
	Stop []string `json:"stop,omitempty"`
}

// ChatResponse represents a chat completion response
type ChatResponse struct {
	// Unique identifier for the completion
	ID string `json:"id"`
	
	// Object type (always "chat.completion")
	Object string `json:"object"`
	
	// Unix timestamp when the completion was created
	Created int64 `json:"created"`
	
	// Model used for the completion
	Model string `json:"model"`
	
	// Choices generated by the model
	Choices []ChatChoice `json:"choices"`
	
	// Token usage information
	Usage TokenUsage `json:"usage"`
	
	// System fingerprint (for consistency)
	SystemFingerprint string `json:"system_fingerprint,omitempty"`
}

// ChatChoice represents a single completion choice
type ChatChoice struct {
	// Index of this choice
	Index int `json:"index"`
	
	// The generated message
	Message ChatMessage `json:"message"`
	
	// Reason why the model stopped generating
	FinishReason string `json:"finish_reason"`
	
	// Log probabilities (if requested)
	LogProbs interface{} `json:"logprobs,omitempty"`
}

// ChatMessage represents a message in the conversation
type ChatMessage struct {
	// Role of the message sender ("system", "user", "assistant", "tool")
	Role string `json:"role"`
	
	// Content of the message
	Content string `json:"content,omitempty"`
	
	// Tool calls made by the assistant
	ToolCalls []ToolCall `json:"tool_calls,omitempty"`
	
	// ID of the tool call this message is responding to (for tool messages)
	ToolCallID *string `json:"tool_call_id,omitempty"`
	
	// Name of the function/tool (for some providers)
	Name *string `json:"name,omitempty"`
}

// ToolCall represents a tool call made by the LLM
type ToolCall struct {
	// Unique identifier for the tool call
	ID string `json:"id"`
	
	// Type of tool call (usually "function")
	Type string `json:"type"`
	
	// Function call details
	Function ToolCallFunction `json:"function"`
}

// ToolCallFunction represents the function details in a tool call
type ToolCallFunction struct {
	// Name of the function to call
	Name string `json:"name"`
	
	// Arguments as a JSON string
	Arguments string `json:"arguments"`
}

// ToolDefinition represents a tool that can be used by the LLM
type ToolDefinition struct {
	// Type of tool (usually "function")
	Type string `json:"type"`
	
	// Function definition
	Function FunctionSchema `json:"function"`
}

// FunctionSchema represents the schema for a function tool
type FunctionSchema struct {
	// Name of the function
	Name string `json:"name"`
	
	// Description of what the function does
	Description string `json:"description"`
	
	// JSON schema for the function parameters
	Parameters FunctionParameters `json:"parameters"`
}

// FunctionParameters represents the parameters schema for a function
type FunctionParameters struct {
	// Type (should be "object")
	Type string `json:"type"`
	
	// Properties defining each parameter
	Properties map[string]PropertySchema `json:"properties"`
	
	// Required parameter names
	Required []string `json:"required,omitempty"`
	
	// Additional properties allowed
	AdditionalProperties bool `json:"additionalProperties,omitempty"`
}

// PropertySchema represents the schema for a single parameter
type PropertySchema struct {
	// Type of the property
	Type string `json:"type"`
	
	// Description of the property
	Description string `json:"description,omitempty"`
	
	// Enum values (for string types)
	Enum []interface{} `json:"enum,omitempty"`
	
	// Items schema (for array types)
	Items *PropertySchema `json:"items,omitempty"`
	
	// Properties (for object types)
	Properties map[string]PropertySchema `json:"properties,omitempty"`
	
	// Default value
	Default interface{} `json:"default,omitempty"`
	
	// Minimum/maximum values (for numeric types)
	Minimum *float64 `json:"minimum,omitempty"`
	Maximum *float64 `json:"maximum,omitempty"`
	
	// Pattern (for string types)
	Pattern string `json:"pattern,omitempty"`
}

// TokenUsage represents token consumption information
type TokenUsage struct {
	// Tokens used in the prompt/input
	PromptTokens int `json:"prompt_tokens"`
	
	// Tokens used in the completion/output
	CompletionTokens int `json:"completion_tokens"`
	
	// Total tokens used
	TotalTokens int `json:"total_tokens"`
}

// StreamEvent represents a single event in a streaming response
type StreamEvent struct {
	// Type of event ("message", "tool_call", "error", "done")
	Type string `json:"type"`
	
	// Event data (varies by type)
	Data interface{} `json:"data,omitempty"`
	
	// Error information (for error events)
	Error error `json:"error,omitempty"`
	
	// Raw event data (for debugging)
	Raw string `json:"raw,omitempty"`
	
	// Timestamp when event was received
	Timestamp time.Time `json:"timestamp"`
}

// StreamChoice represents a streaming completion choice
type StreamChoice struct {
	// Index of this choice
	Index int `json:"index"`
	
	// Delta containing the incremental message content
	Delta ChatMessage `json:"delta"`
	
	// Reason why the model stopped (only in final chunk)
	FinishReason *string `json:"finish_reason,omitempty"`
}

// StreamResponse represents a streaming chat completion chunk
type StreamResponse struct {
	// Unique identifier for the completion
	ID string `json:"id"`
	
	// Object type (always "chat.completion.chunk")
	Object string `json:"object"`
	
	// Unix timestamp when the chunk was created
	Created int64 `json:"created"`
	
	// Model used for the completion
	Model string `json:"model"`
	
	// Choices in this chunk
	Choices []StreamChoice `json:"choices"`
}

// ModelsResponse represents a list of available models
type ModelsResponse struct {
	// Object type (always "list")
	Object string `json:"object"`
	
	// List of model information
	Data []ModelInfo `json:"data"`
}

// ModelInfo represents information about a specific model
type ModelInfo struct {
	// Unique model identifier
	ID string `json:"id"`
	
	// Object type (always "model")
	Object string `json:"object"`
	
	// Unix timestamp when the model was created
	Created int64 `json:"created"`
	
	// Organization that owns the model
	OwnedBy string `json:"owned_by"`
	
	// Additional model metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// ErrorResponse represents an API error response
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// APIError represents an API error
type APIError struct {
	// Error message
	Message string `json:"message"`
	
	// Error type/code
	Type string `json:"type"`
	
	// Error code
	Code string `json:"code,omitempty"`
	
	// HTTP status code
	StatusCode int `json:"status_code,omitempty"`
}

// Implement error interface for APIError
func (e *APIError) Error() string {
	return e.Message
}

// ParseArguments parses the JSON arguments string into a map
func (t *ToolCallFunction) ParseArguments() (map[string]interface{}, error) {
	if t.Arguments == "" {
		return make(map[string]interface{}), nil
	}
	
	var args map[string]interface{}
	err := json.Unmarshal([]byte(t.Arguments), &args)
	if err != nil {
		return nil, err
	}
	
	return args, nil
}

// MarshalArguments converts a map of arguments to a JSON string
func (t *ToolCallFunction) MarshalArguments(args map[string]interface{}) error {
	if args == nil {
		t.Arguments = ""
		return nil
	}
	
	data, err := json.Marshal(args)
	if err != nil {
		return err
	}
	
	t.Arguments = string(data)
	return nil
}

// IsSystemMessage returns true if this is a system message
func (m *ChatMessage) IsSystemMessage() bool {
	return m.Role == "system"
}

// IsUserMessage returns true if this is a user message
func (m *ChatMessage) IsUserMessage() bool {
	return m.Role == "user"
}

// IsAssistantMessage returns true if this is an assistant message
func (m *ChatMessage) IsAssistantMessage() bool {
	return m.Role == "assistant"
}

// IsToolMessage returns true if this is a tool result message
func (m *ChatMessage) IsToolMessage() bool {
	return m.Role == "tool"
}

// HasToolCalls returns true if this message contains tool calls
func (m *ChatMessage) HasToolCalls() bool {
	return len(m.ToolCalls) > 0
}

// GetToolCallIDs returns the IDs of all tool calls in this message
func (m *ChatMessage) GetToolCallIDs() []string {
	var ids []string
	for _, tc := range m.ToolCalls {
		ids = append(ids, tc.ID)
	}
	return ids
}

// Anthropic-specific types for API compatibility

// AnthropicRequest represents an Anthropic API request
type AnthropicRequest struct {
	// Model to use for completion
	Model string `json:"model"`
	
	// Maximum tokens to generate
	MaxTokens int `json:"max_tokens"`
	
	// Messages in the conversation
	Messages []AnthropicMessage `json:"messages"`
	
	// System prompt (separate from messages in Anthropic)
	System string `json:"system,omitempty"`
	
	// Tools available for the model to use
	Tools []AnthropicTool `json:"tools,omitempty"`
	
	// Sampling temperature
	Temperature *float64 `json:"temperature,omitempty"`
	
	// Whether to stream the response
	Stream bool `json:"stream,omitempty"`
	
	// Top-p nucleus sampling parameter
	TopP *float64 `json:"top_p,omitempty"`
	
	// Stop sequences
	StopSequences []string `json:"stop_sequences,omitempty"`
}

// AnthropicMessage represents a message in Anthropic format
type AnthropicMessage struct {
	// Role of the message sender
	Role string `json:"role"`
	
	// Content of the message
	Content string `json:"content"`
}

// AnthropicTool represents a tool definition in Anthropic format
type AnthropicTool struct {
	// Name of the tool
	Name string `json:"name"`
	
	// Description of what the tool does
	Description string `json:"description"`
	
	// JSON schema for the tool input
	InputSchema FunctionParameters `json:"input_schema"`
}

// AnthropicResponse represents an Anthropic API response
type AnthropicResponse struct {
	// Unique identifier for the completion
	ID string `json:"id"`
	
	// Type of response
	Type string `json:"type"`
	
	// Role of the response
	Role string `json:"role"`
	
	// Model used for the completion
	Model string `json:"model"`
	
	// Content blocks in the response
	Content []AnthropicContent `json:"content"`
	
	// Reason the model stopped generating
	StopReason string `json:"stop_reason"`
	
	// Stop sequence that was matched (if any)
	StopSequence *string `json:"stop_sequence,omitempty"`
	
	// Token usage information
	Usage AnthropicUsage `json:"usage"`
}

// AnthropicContent represents a content block in Anthropic response
type AnthropicContent struct {
	// Type of content block
	Type string `json:"type"`
	
	// Text content (for text blocks)
	Text string `json:"text,omitempty"`
	
	// Tool use ID (for tool_use blocks)
	ID string `json:"id,omitempty"`
	
	// Tool name (for tool_use blocks)
	Name string `json:"name,omitempty"`
	
	// Tool input (for tool_use blocks)
	Input json.RawMessage `json:"input,omitempty"`
}

// AnthropicUsage represents token usage in Anthropic format
type AnthropicUsage struct {
	// Input tokens used
	InputTokens int `json:"input_tokens"`
	
	// Output tokens used
	OutputTokens int `json:"output_tokens"`
}